/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

/**
 *
 * @author juanp
 */
public class Facturar extends javax.swing.JPanel {
    GUIPrincipal p;
    IzqAdmin i;
    /**
     * Creates new form Facturar
     */
    public Facturar(GUIPrincipal guiP, IzqAdmin iA) {
        p = guiP;
        i = iA;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LBLIZIcars = new javax.swing.JLabel();
        btnGenerarReporte = new javax.swing.JPanel();
        LBLiniSesion1 = new javax.swing.JLabel();
        LBLiniSesion3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setName(""); // NOI18N
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel1formMouseEntered(evt);
            }
        });

        LBLIZIcars.setFont(new java.awt.Font("Roboto Black", 1, 36)); // NOI18N
        LBLIZIcars.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cositoLogin.png"))); // NOI18N
        LBLIZIcars.setText(" IZI CARS");

        btnGenerarReporte.setBackground(new java.awt.Color(71, 193, 255));
        btnGenerarReporte.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGenerarReporte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGenerarReporteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGenerarReporteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGenerarReporteMouseExited(evt);
            }
        });

        LBLiniSesion1.setBackground(new java.awt.Color(71, 193, 255));
        LBLiniSesion1.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        LBLiniSesion1.setForeground(new java.awt.Color(255, 255, 255));
        LBLiniSesion1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LBLiniSesion1.setText("GENERAR");

        javax.swing.GroupLayout btnGenerarReporteLayout = new javax.swing.GroupLayout(btnGenerarReporte);
        btnGenerarReporte.setLayout(btnGenerarReporteLayout);
        btnGenerarReporteLayout.setHorizontalGroup(
            btnGenerarReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LBLiniSesion1, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
        );
        btnGenerarReporteLayout.setVerticalGroup(
            btnGenerarReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LBLiniSesion1, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        LBLiniSesion3.setFont(new java.awt.Font("Roboto Black", 1, 36)); // NOI18N
        LBLiniSesion3.setText("GENERAR PDF DE FACTURAS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LBLIZIcars, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LBLiniSesion3, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGenerarReporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(LBLIZIcars, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(LBLiniSesion3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnGenerarReporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerarReporteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGenerarReporteMouseClicked
        // TODO add your handling code here:
        //Logica XD, nose aqi genere las facturas

    }//GEN-LAST:event_btnGenerarReporteMouseClicked

    private void btnGenerarReporteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGenerarReporteMouseEntered
        // TODO add your handling code here:
        btnGenerarReporte.setBackground(new java.awt.Color(0, 136, 255));
    }//GEN-LAST:event_btnGenerarReporteMouseEntered

    private void btnGenerarReporteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGenerarReporteMouseExited
        // TODO add your handling code here:
        btnGenerarReporte.setBackground(new java.awt.Color(71, 193, 255));
    }//GEN-LAST:event_btnGenerarReporteMouseExited

    private void jPanel1formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1formMouseEntered
        // TODO add your handling code here:
        i.facturarAux();
    }//GEN-LAST:event_jPanel1formMouseEntered


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LBLIZIcars;
    private javax.swing.JLabel LBLiniSesion1;
    private javax.swing.JLabel LBLiniSesion3;
    private javax.swing.JPanel btnGenerarReporte;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
