/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import javax.swing.ImageIcon;

/**
 *
 * @author juanp
 */
public class PanelCarrito extends javax.swing.JPanel {

    /**
     * Creates new form PanelCarrito
     */
    public PanelCarrito() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblImagen = new javax.swing.JLabel();
        lblPlaca = new javax.swing.JLabel();
        lblMarca = new javax.swing.JLabel();
        lblModelo = new javax.swing.JLabel();
        lblColor = new javax.swing.JLabel();
        Agregado = new javax.swing.JCheckBox();
        lblID1 = new javax.swing.JLabel();
        lblMarca1 = new javax.swing.JLabel();
        lblModelo1 = new javax.swing.JLabel();
        lblColor1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(71, 193, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(lblImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 80));

        lblPlaca.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        lblPlaca.setText("ID:");
        add(lblPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 80, -1));

        lblMarca.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        lblMarca.setText("Marca:");
        add(lblMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 80, -1));

        lblModelo.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        lblModelo.setText("Modelo:");
        add(lblModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 80, -1));

        lblColor.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        lblColor.setText("Color:");
        add(lblColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 80, -1));

        Agregado.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        Agregado.setText("Agregar");
        Agregado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregadoActionPerformed(evt);
            }
        });
        add(Agregado, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, -1, 30));

        lblID1.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblID1.setText("Placa:");
        add(lblID1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 50, -1));

        lblMarca1.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblMarca1.setText("Marca:");
        add(lblMarca1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 50, -1));

        lblModelo1.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblModelo1.setText("Modelo:");
        add(lblModelo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 50, -1));

        lblColor1.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblColor1.setText("Color:");
        add(lblColor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 50, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void AgregadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AgregadoActionPerformed

    public void setCarrito(String rutaImagen, String id, String marca, String modelo, String color)
    {
        ImageIcon imagen = new ImageIcon(getClass().getResource(rutaImagen));
        lblImagen.setIcon(imagen);
        lblPlaca.setText(id);
        lblMarca.setText(marca);
        lblModelo.setText(modelo);
        lblColor.setText(color);
    }
    
    public String getID()
    {
        return lblPlaca.getText();
    }
    
    public boolean estaSeleccionado()
    {
        return Agregado.isSelected();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Agregado;
    private javax.swing.JLabel lblColor;
    private javax.swing.JLabel lblColor1;
    private javax.swing.JLabel lblID1;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblMarca1;
    private javax.swing.JLabel lblModelo;
    private javax.swing.JLabel lblModelo1;
    private javax.swing.JLabel lblPlaca;
    // End of variables declaration//GEN-END:variables
}
