/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import javax.swing.ImageIcon;

/**
 *
 * @author juanp
 */
public class PanelCarritoInventario extends javax.swing.JPanel {
    GUIPrincipal p;
    IzqAdmin i;
    /**
     * Creates new form PanelCarritoCompra
     */
    public PanelCarritoInventario(GUIPrincipal guiP, IzqAdmin iA) {
        p = guiP;
        i = iA;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblImagen = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        lblMarca = new javax.swing.JLabel();
        lblModelo = new javax.swing.JLabel();
        lblColor = new javax.swing.JLabel();
        lblID1 = new javax.swing.JLabel();
        lblMarca1 = new javax.swing.JLabel();
        lblModelo1 = new javax.swing.JLabel();
        lblColor1 = new javax.swing.JLabel();
        btnVer = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(71, 193, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(lblImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 80));

        lblID.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        lblID.setText("ID:");
        jPanel1.add(lblID, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 80, -1));

        lblMarca.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        lblMarca.setText("Marca:");
        jPanel1.add(lblMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 80, -1));

        lblModelo.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        lblModelo.setText("Modelo:");
        jPanel1.add(lblModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 80, -1));

        lblColor.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        lblColor.setText("Color:");
        jPanel1.add(lblColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 80, -1));

        lblID1.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblID1.setText("ID:");
        jPanel1.add(lblID1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 50, -1));

        lblMarca1.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblMarca1.setText("Marca:");
        jPanel1.add(lblMarca1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 50, -1));

        lblModelo1.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblModelo1.setText("Modelo:");
        jPanel1.add(lblModelo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 50, -1));

        lblColor1.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblColor1.setText("Color:");
        jPanel1.add(lblColor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 50, -1));

        btnVer.setBackground(new java.awt.Color(0, 136, 255));
        btnVer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVerMouseExited(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ver");

        javax.swing.GroupLayout btnVerLayout = new javax.swing.GroupLayout(btnVer);
        btnVer.setLayout(btnVerLayout);
        btnVerLayout.setHorizontalGroup(
            btnVerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        btnVerLayout.setVerticalGroup(
            btnVerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
        );

        jPanel1.add(btnVer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 150, 20));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 200));
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVerMouseEntered
        // TODO add your handling code here:
        btnVer.setBackground(new java.awt.Color(71, 193, 255));
    }//GEN-LAST:event_btnVerMouseEntered

    private void btnVerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVerMouseExited
        // TODO add your handling code here:
        btnVer.setBackground(new java.awt.Color(0, 136, 255));
    }//GEN-LAST:event_btnVerMouseExited

    private void btnVerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVerMouseClicked
        // TODO add your handling code here:
        p.ShowJPanel(new VistaModificar(p,i,lblID.getText()));
    }//GEN-LAST:event_btnVerMouseClicked
    
    
    public void setCarrito(String rutaImagen, String id, String marca, String modelo, String color)
    {
        ImageIcon imagen = new ImageIcon(getClass().getResource(rutaImagen));
        lblImagen.setIcon(imagen);
        lblID.setText(id);
        lblMarca.setText(marca);
        lblModelo.setText(modelo);
        lblColor.setText(color);
    }
    
    public String getID()
    {
        return lblID.getText();
    }
    
    public String getMarca()
    {
        return lblMarca.getText();
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnVer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblColor;
    private javax.swing.JLabel lblColor1;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblID1;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblMarca1;
    private javax.swing.JLabel lblModelo;
    private javax.swing.JLabel lblModelo1;
    // End of variables declaration//GEN-END:variables
}
