/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import java.awt.Color;

/**
 *
 * @author juanp
 */
public class RegistrarEmpleado extends javax.swing.JPanel {
    GUIPrincipal p;
    /**
     * Creates new form RegistrarEmpleado
     */
    public RegistrarEmpleado(GUIPrincipal guiP) {
        p = guiP;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LBLIZIcars = new javax.swing.JLabel();
        LBLiniSesion3 = new javax.swing.JLabel();
        btnVolver = new javax.swing.JPanel();
        LBLiniSesion2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtNombres = new javax.swing.JTextField();
        LBLiniSesion = new javax.swing.JLabel();
        LBLiniSesion1 = new javax.swing.JLabel();
        txtApellidoPaterno = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        txtApellidoMaterno = new javax.swing.JTextField();
        LBLiniSesion4 = new javax.swing.JLabel();
        btnCrearEmpleado = new javax.swing.JPanel();
        LBLiniSesion5 = new javax.swing.JLabel();
        LBLiniSesion6 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        txtCedula = new javax.swing.JTextField();
        LBLiniSesion7 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        LBLiniSesion8 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        LBLiniSesion9 = new javax.swing.JLabel();
        txtPorcentaje = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        txtContrasenia = new javax.swing.JTextField();
        LBLiniSesion10 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LBLIZIcars.setFont(new java.awt.Font("Roboto Black", 1, 36)); // NOI18N
        LBLIZIcars.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cositoLogin.png"))); // NOI18N
        LBLIZIcars.setText(" IZI CARS");
        add(LBLIZIcars, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 250, 60));

        LBLiniSesion3.setFont(new java.awt.Font("Roboto Black", 1, 36)); // NOI18N
        LBLiniSesion3.setText("REGISTRAR EMPLEADO");
        add(LBLiniSesion3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 450, 60));

        btnVolver.setBackground(new java.awt.Color(71, 193, 255));
        btnVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVolverMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVolverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVolverMouseExited(evt);
            }
        });

        LBLiniSesion2.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        LBLiniSesion2.setForeground(new java.awt.Color(255, 255, 255));
        LBLiniSesion2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LBLiniSesion2.setText("< VOLVER");

        javax.swing.GroupLayout btnVolverLayout = new javax.swing.GroupLayout(btnVolver);
        btnVolver.setLayout(btnVolverLayout);
        btnVolverLayout.setHorizontalGroup(
            btnVolverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnVolverLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(LBLiniSesion2, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnVolverLayout.setVerticalGroup(
            btnVolverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnVolverLayout.createSequentialGroup()
                .addComponent(LBLiniSesion2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 630, -1, 70));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 230, 10));

        txtNombres.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        txtNombres.setForeground(new java.awt.Color(204, 204, 204));
        txtNombres.setText("Ingrese sus nombres");
        txtNombres.setBorder(null);
        txtNombres.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtNombresMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtNombresMousePressed(evt);
            }
        });
        txtNombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombresActionPerformed(evt);
            }
        });
        add(txtNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 210, 30));

        LBLiniSesion.setFont(new java.awt.Font("Roboto Light", 1, 24)); // NOI18N
        LBLiniSesion.setText("NOMBRES");
        add(LBLiniSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 200, 60));

        LBLiniSesion1.setFont(new java.awt.Font("Roboto Light", 1, 24)); // NOI18N
        LBLiniSesion1.setText("PRIMER APELLIDO");
        add(LBLiniSesion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, 230, 60));

        txtApellidoPaterno.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        txtApellidoPaterno.setForeground(new java.awt.Color(204, 204, 204));
        txtApellidoPaterno.setText("Ingrese su primer apellido");
        txtApellidoPaterno.setBorder(null);
        txtApellidoPaterno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtApellidoPaternoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtApellidoPaternoMousePressed(evt);
            }
        });
        txtApellidoPaterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoPaternoActionPerformed(evt);
            }
        });
        add(txtApellidoPaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, 210, 30));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 380, 230, 10));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 480, 230, 10));

        txtApellidoMaterno.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        txtApellidoMaterno.setForeground(new java.awt.Color(204, 204, 204));
        txtApellidoMaterno.setText("Ingrese su segundo apellido");
        txtApellidoMaterno.setToolTipText("");
        txtApellidoMaterno.setBorder(null);
        txtApellidoMaterno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtApellidoMaternoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtApellidoMaternoMousePressed(evt);
            }
        });
        txtApellidoMaterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoMaternoActionPerformed(evt);
            }
        });
        add(txtApellidoMaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 450, 210, 30));

        LBLiniSesion4.setFont(new java.awt.Font("Roboto Light", 1, 24)); // NOI18N
        LBLiniSesion4.setText("SEGUNDO APELLIDO");
        add(LBLiniSesion4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 390, 240, 60));

        btnCrearEmpleado.setBackground(new java.awt.Color(71, 193, 255));
        btnCrearEmpleado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCrearEmpleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCrearEmpleadoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCrearEmpleadoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCrearEmpleadoMouseExited(evt);
            }
        });

        LBLiniSesion5.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        LBLiniSesion5.setForeground(new java.awt.Color(255, 255, 255));
        LBLiniSesion5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LBLiniSesion5.setText("REGISTRAR");

        javax.swing.GroupLayout btnCrearEmpleadoLayout = new javax.swing.GroupLayout(btnCrearEmpleado);
        btnCrearEmpleado.setLayout(btnCrearEmpleadoLayout);
        btnCrearEmpleadoLayout.setHorizontalGroup(
            btnCrearEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnCrearEmpleadoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(LBLiniSesion5, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnCrearEmpleadoLayout.setVerticalGroup(
            btnCrearEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCrearEmpleadoLayout.createSequentialGroup()
                .addComponent(LBLiniSesion5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        add(btnCrearEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 630, 260, 70));

        LBLiniSesion6.setFont(new java.awt.Font("Roboto Light", 1, 24)); // NOI18N
        LBLiniSesion6.setText("CEDULA");
        add(LBLiniSesion6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 490, 240, 60));

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 580, 230, 10));

        txtCedula.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        txtCedula.setForeground(new java.awt.Color(204, 204, 204));
        txtCedula.setText("Ingrese su cedula");
        txtCedula.setToolTipText("");
        txtCedula.setBorder(null);
        txtCedula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtCedulaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtCedulaMousePressed(evt);
            }
        });
        txtCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCedulaActionPerformed(evt);
            }
        });
        add(txtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 550, 210, 30));

        LBLiniSesion7.setFont(new java.awt.Font("Roboto Light", 1, 24)); // NOI18N
        LBLiniSesion7.setText("CORREO");
        add(LBLiniSesion7, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 190, 200, 60));

        txtCorreo.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        txtCorreo.setForeground(new java.awt.Color(204, 204, 204));
        txtCorreo.setText("Ingrese su correo electronico");
        txtCorreo.setBorder(null);
        txtCorreo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtCorreoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtCorreoMousePressed(evt);
            }
        });
        txtCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoActionPerformed(evt);
            }
        });
        add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 250, 210, 30));

        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 280, 230, 10));

        LBLiniSesion8.setFont(new java.awt.Font("Roboto Light", 1, 24)); // NOI18N
        LBLiniSesion8.setText("TELEFONO");
        add(LBLiniSesion8, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 290, 200, 60));

        txtTelefono.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        txtTelefono.setForeground(new java.awt.Color(204, 204, 204));
        txtTelefono.setText("Ingrese su numero telefonico");
        txtTelefono.setBorder(null);
        txtTelefono.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtTelefonoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtTelefonoMousePressed(evt);
            }
        });
        txtTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoActionPerformed(evt);
            }
        });
        add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 350, 210, 30));

        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));
        add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 380, 230, 10));

        LBLiniSesion9.setFont(new java.awt.Font("Roboto Light", 1, 24)); // NOI18N
        LBLiniSesion9.setText("PORCENTAJE VENTAS");
        add(LBLiniSesion9, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 390, 270, 60));

        txtPorcentaje.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        txtPorcentaje.setForeground(new java.awt.Color(204, 204, 204));
        txtPorcentaje.setText("Ingrese su bonificacion por venta");
        txtPorcentaje.setBorder(null);
        txtPorcentaje.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtPorcentajeMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtPorcentajeMousePressed(evt);
            }
        });
        txtPorcentaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPorcentajeActionPerformed(evt);
            }
        });
        add(txtPorcentaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 450, 210, 30));

        jSeparator7.setForeground(new java.awt.Color(0, 0, 0));
        add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 480, 230, 10));

        jSeparator8.setForeground(new java.awt.Color(0, 0, 0));
        add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 580, 230, 10));

        txtContrasenia.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        txtContrasenia.setForeground(new java.awt.Color(204, 204, 204));
        txtContrasenia.setText("Ingrese su contraseña");
        txtContrasenia.setBorder(null);
        txtContrasenia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtContraseniaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtContraseniaMousePressed(evt);
            }
        });
        txtContrasenia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContraseniaActionPerformed(evt);
            }
        });
        add(txtContrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 550, 210, 30));

        LBLiniSesion10.setFont(new java.awt.Font("Roboto Light", 1, 24)); // NOI18N
        LBLiniSesion10.setText("CONTRASEÑA");
        add(LBLiniSesion10, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 490, 270, 60));
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMouseClicked
        // TODO add your handling code here:
        p.ShowJPanel(new IniciarSesion(p)); //a
    }//GEN-LAST:event_btnVolverMouseClicked

    private void btnVolverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMouseEntered
        // TODO add your handling code here:
        btnVolver.setBackground(Color.red);
    }//GEN-LAST:event_btnVolverMouseEntered

    private void btnVolverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMouseExited
        // TODO add your handling code here:
        btnVolver.setBackground(new java.awt.Color(71, 193, 255));
    }//GEN-LAST:event_btnVolverMouseExited

    private void txtNombresMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombresMousePressed
        // TODO add your handling code here:
        if(txtNombres.getText().equals("Ingrese sus nombres")){
            txtNombres.setText("");
            txtNombres.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtNombresMousePressed

    private void txtNombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombresActionPerformed

    private void txtApellidoPaternoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtApellidoPaternoMousePressed
        // TODO add your handling code here:
        if(txtApellidoPaterno.getText().equals("Ingrese su primer apellido")){
            txtApellidoPaterno.setText("");
            txtApellidoPaterno.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtApellidoPaternoMousePressed

    private void txtApellidoPaternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoPaternoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoPaternoActionPerformed

    private void txtApellidoMaternoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtApellidoMaternoMousePressed
        // TODO add your handling code here:
        if(txtApellidoMaterno.getText().equals("Ingrese su segundo apellido")){
            txtApellidoMaterno.setText("");
            txtApellidoMaterno.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtApellidoMaternoMousePressed

    private void txtApellidoMaternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoMaternoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoMaternoActionPerformed

    private void btnCrearEmpleadoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearEmpleadoMouseEntered
        // TODO add your handling code here:
        btnCrearEmpleado.setBackground(Color.green);
    }//GEN-LAST:event_btnCrearEmpleadoMouseEntered

    private void btnCrearEmpleadoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearEmpleadoMouseExited
        // TODO add your handling code here:
        btnCrearEmpleado.setBackground(new java.awt.Color(71, 193, 255));
    }//GEN-LAST:event_btnCrearEmpleadoMouseExited

    private void txtCedulaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCedulaMousePressed
        // TODO add your handling code here:
        if(txtCedula.getText().equals("Ingrese su cedula")){
            txtCedula.setText("");
            txtCedula.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtCedulaMousePressed

    private void txtCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaActionPerformed

    private void txtCorreoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCorreoMousePressed
        // TODO add your handling code here:
        if(txtCorreo.getText().equals("Ingrese su correo electronico")){
            txtCorreo.setText("");
            txtCorreo.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtCorreoMousePressed

    private void txtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoActionPerformed

    private void txtTelefonoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTelefonoMousePressed
        // TODO add your handling code here:
        if(txtTelefono.getText().equals("Ingrese su numero telefonico")){
            txtTelefono.setText("");
            txtTelefono.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtTelefonoMousePressed

    private void txtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoActionPerformed

    private void txtPorcentajeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPorcentajeMousePressed
        // TODO add your handling code here:
        if(txtPorcentaje.getText().equals("Ingrese su bonificacion por venta")){
            txtPorcentaje.setText("");
            txtPorcentaje.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtPorcentajeMousePressed

    private void txtPorcentajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPorcentajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPorcentajeActionPerformed

    private void txtContraseniaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtContraseniaMousePressed
        // TODO add your handling code here:
        if(txtContrasenia.getText().equals("Ingrese su contraseña")){
            txtContrasenia.setText("");
            txtContrasenia.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtContraseniaMousePressed

    private void txtContraseniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContraseniaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContraseniaActionPerformed

    private void txtNombresMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombresMouseExited
        // TODO add your handling code here:
        if(txtNombres.getText().isEmpty()){
            txtNombres.setText("Ingrese sus nombres");
            txtNombres.setForeground(new java.awt.Color(204,204,204));
        }
    }//GEN-LAST:event_txtNombresMouseExited

    private void txtApellidoPaternoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtApellidoPaternoMouseExited
        // TODO add your handling code here:
        if(txtApellidoPaterno.getText().isEmpty()){
            txtApellidoPaterno.setText("Ingrese su primer apellido");
            txtApellidoPaterno.setForeground(new java.awt.Color(204,204,204));
        }
    }//GEN-LAST:event_txtApellidoPaternoMouseExited

    private void txtApellidoMaternoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtApellidoMaternoMouseExited
        // TODO add your handling code here:
        if(txtApellidoMaterno.getText().isEmpty()){
            txtApellidoMaterno.setText("Ingrese su segundo apellido");
            txtApellidoMaterno.setForeground(new java.awt.Color(204,204,204));
        }
    }//GEN-LAST:event_txtApellidoMaternoMouseExited

    private void txtCedulaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCedulaMouseExited
        // TODO add your handling code here:
        if(txtCedula.getText().isEmpty()){
            txtCedula.setText("Ingrese su cedula");
            txtCedula.setForeground(new java.awt.Color(204,204,204));
        }
    }//GEN-LAST:event_txtCedulaMouseExited

    private void txtCorreoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCorreoMouseExited
        // TODO add your handling code here:
        if(txtCorreo.getText().isEmpty()){
            txtCorreo.setText("Ingrese su correo electronico");
            txtCorreo.setForeground(new java.awt.Color(204,204,204));
        }
    }//GEN-LAST:event_txtCorreoMouseExited

    private void txtTelefonoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTelefonoMouseExited
        // TODO add your handling code here:
        if(txtTelefono.getText().isEmpty()){
            txtTelefono.setText("Ingrese su numero telefonico");
            txtTelefono.setForeground(new java.awt.Color(204,204,204));
        }
    }//GEN-LAST:event_txtTelefonoMouseExited

    private void txtPorcentajeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPorcentajeMouseExited
        // TODO add your handling code here:
        if(txtPorcentaje.getText().isEmpty()){
            txtPorcentaje.setText("Ingrese su bonificacion por venta");
            txtPorcentaje.setForeground(new java.awt.Color(204,204,204));
        }
    }//GEN-LAST:event_txtPorcentajeMouseExited

    private void txtContraseniaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtContraseniaMouseExited
        // TODO add your handling code here:
        if(txtContrasenia.getText().isEmpty()){
            txtContrasenia.setText("Ingrese su contraseña");
            txtContrasenia.setForeground(new java.awt.Color(204,204,204));
        }
    }//GEN-LAST:event_txtContraseniaMouseExited

    private void btnCrearEmpleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearEmpleadoMouseClicked
        // TODO add your handling code here:
        String nombre = txtNombres.getText();
        String apellidoPaterno = txtApellidoPaterno.getText();
        String apellidoMaterno = txtApellidoMaterno.getText();
        String correo = txtCorreo.getText();
        String telefono = txtTelefono.getText();
        String cedula = txtCedula.getText();
        String contra = txtContrasenia.getText();
        //double porcentaje = Double.parseDouble(txtPorcentaje.getText());
        
        //Logica para registrar xd
        
        if(true)//logica de si si se agrego xd
        {
            p.ShowJPanel(new IniciarSesion(p));
        }
        
    }//GEN-LAST:event_btnCrearEmpleadoMouseClicked
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LBLIZIcars;
    private javax.swing.JLabel LBLiniSesion;
    private javax.swing.JLabel LBLiniSesion1;
    private javax.swing.JLabel LBLiniSesion10;
    private javax.swing.JLabel LBLiniSesion2;
    private javax.swing.JLabel LBLiniSesion3;
    private javax.swing.JLabel LBLiniSesion4;
    private javax.swing.JLabel LBLiniSesion5;
    private javax.swing.JLabel LBLiniSesion6;
    private javax.swing.JLabel LBLiniSesion7;
    private javax.swing.JLabel LBLiniSesion8;
    private javax.swing.JLabel LBLiniSesion9;
    private javax.swing.JPanel btnCrearEmpleado;
    private javax.swing.JPanel btnVolver;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTextField txtApellidoMaterno;
    private javax.swing.JTextField txtApellidoPaterno;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtContrasenia;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtPorcentaje;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
